### ISSUE TITLE
Freeathome gone?

### ISSUE THREAD

**Issue by RichardvanGestel** [jheling/freeathome#102]
Hi,

In HomeAssitant core-2021.5.5, Freeathome is a nice and working integration

In core-2021.6.0 it is gone???!?!?!?

Please help...

**Comment by j0rdyk** [comment]
Same here since the new update. 
"The system cannot restart because the configuration is not valid: Component error: freeathome - Integration 'freeathome' not found."

Running supervisor-2021.05.4
core-2021.6.0
Home Assistant OS 5.13

**Comment by RichardvanGestel** [comment]
I made a fresh installation of home assistant, freeathome can be installed there as normal.

**Comment by Tho85** [comment]
The component continues to work for me after upgrading to 2021.06.0.

Which version of the freeathome component do you use? Due to a change in the latest Home Assistant version (2021.6.0), only the most current version from master branch works. Could you update the component and try again?

If it doesn't work, it would be great if you could provide a log file from Home Assistant startup.

**Comment by RichardvanGestel** [comment]
@Tho85
After installing the most recent version of free@home, the update was indeed successful. thanks!!!

**Comment by j0rdyk** [comment]
Thankyou guys, worked great!

**Comment by RichardvanGestel** [comment]
Solved
