### ISSUE TITLE
Power Outlet Shown as Light

### ISSUE THREAD

**Issue by Ruko2010** [jheling/freeathome#168]
Hi, I have a "Schaltaktor 4-fach" to control 4 Power Outlets. But in HA they are shown as lights. So If I tell Siri to turn off all lights in the Living Room, also my Television gets turned off. Can I change this behavior? I already changed the Icon, but did not found a way to change the "light".
I'm really new to HA so I hope this is not a dump question 😃.

Thanks for the help
![IMG_5801](https://github.com/jheling/freeathome/assets/2239440/c8c48962-c695-49f4-8a19-a674d0dac53c)
![IMG_5800](https://github.com/jheling/freeathome/assets/2239440/2c9db7e2-601f-41d5-ab3c-ede02811e4c5)

**Comment by Ruko2010** [comment]
@jheling I see, that there is a [PR](https://github.com/jheling/freeathome/pull/141) that maybe fixes this. Can you tell me, why it is never merged?

**Comment by derjoerg** [comment]
Hey,
from my perspective ALL switch-actuators from free@home should be created in HA as switches and not as lights as of today because - at the end - nobody can automatically find out if a switch-actuator in F@H is used for a light, a power-outlet or something else.
If they are created as switches in HA people can easily use the "switch-as-x" helpers to create the necessary light, fan, ... as used in the specific home

**Comment by EnricoBilla** [comment]
@derjoerg Yes you are right, in the PR I opened I did the opposite because for my use case it would have been way easier to list all the devices I wanted to be switches rather than the vice versa

**Comment by Ruko2010** [comment]
With PR #169 it works like charm. Just have to change the switches which are lights via https://www.home-assistant.io/integrations/switch_as_x/ after the initial setup.
