### ISSUE TITLE
Ports in use

### ISSUE THREAD

**Issue by tbloth** [jheling/freeathome#53]
More a general question.
It looks like OpenHAB uses Port 5280 (at least my neighbor told me) where I can see 5222 hard codes in freeathome. What's the difference? 
nmap shows both ports open at my SysAP

Thanks!

**Comment by jheling** [comment]
I cannot remember why I started with 5222 as the port for the connection, maybe because this is used by slixmpp.  I have used the project of Stefan Stadlberger (https://github.com/sstadlberger/home) for figuring out how the free@home interface works. 5222 seems to be the official port for an xmpp client connection over tcp. 5280 is used for the BOSH protocol ( Bidirectional-streams Over Synchronous HTTP).  I think openhab uses this connection method.

**Comment by tbloth** [comment]
Yeah, thanks. Makes sense!

**Comment by miezie** [comment]
Does it: https://en.wikipedia.org/wiki/BOSH_(protocol) ?

;)
