### ISSUE TITLE
Any way to discover Sensor units (button without activator)

### ISSUE THREAD

**Issue by SuperMaximus1984** [jheling/freeathome#59]
Hello! 
In my case, simple Sensors are not recognized by your component.
I have a plan to use automation based on Sensor key pressed (or not pressed). Please help to discover them in HA.
Thank you!

**Comment by jheling** [comment]
Hello, which devices are we talking about?

**Comment by dprauser** [comment]
I am talking about the 7" Display.
FAH also offer a 4.3" Version but I don't have one so I don't know if this version also offers messages.

https://www.busch-jaeger.de/produktuebersicht?tx_nlbjproducts_catalog%5Baction%5D=show&tx_nlbjproducts_catalog%5BcatBjeProdukt%5D=4362&tx_nlbjproducts_catalog%5Bcontroller%5D=CatStdArtikel&cHash=d69ee3b9b9ae061b761d4ec00c763f10

**Comment by victorclaessen** [comment]
I assume @SuperMaximus1984 means sensor-only devices like [6221/1.0](https://www.busch-jaeger.de/en/online-catalogue/product-overview?tx_nlbjproducts_catalog%5Baction%5D=show&tx_nlbjproducts_catalog%5BcatBjeProdukt%5D=14953&tx_nlbjproducts_catalog%5Bcontroller%5D=CatStdArtikel&cHash=dbc5d2701646920e45f304f05f671553).

**Comment by miezie** [comment]
Why this difficult solution while you could build a template switch in HA which triggers wat ever you want in HA and then start the scripting? Way more robust then your idea. 

The switch can be exposed via emulated hue.

**Comment by TribunMaximus** [comment]
Hi there,

I'm trying to implement "Sensoreinheit 1-fach" (e.g. #ABB700DD6876) and "Sensoreinheit 2-fach" (e.g. #ABB700DC8CAA) into HA. The problem: they will be shown in HA as a binary sensor and not as a light.
Any chance to change this?

Many thanks!
Br
Jens

**Comment by Tho85** [comment]
That's correct. These units are only sensors and do not have the circuitry (relay etc.) to control a light on their own. That's why they show up as a binary sensor only.

A [Sensor/Schaltaktor 1/1-fach](https://www.busch-jaeger.de/produktuebersicht?tx_nlbjproducts_catalog%5Baction%5D=show&tx_nlbjproducts_catalog%5BcatBjeProdukt%5D=3662&tx_nlbjproducts_catalog%5BcatStdArtikel%5D=3881&tx_nlbjproducts_catalog%5Bcontroller%5D=CatStdArtikel&cHash=ebcad9dad5b89b52623522647e2f3c56) on the other hand would show up as a binary sensor and a light.
