### ISSUE TITLE
Binary sensor doesn't work

### ISSUE THREAD

**Issue by JvD12** [jheling/freeathome#81]
It looks like binary sensors does not work as intended. My 2 channel digital input is detected in Home Assistant but the entity names are strange, the first is called binary_sensor. and the second binary_sensor.2 
Looks like something went wrong with naming. 

I'm also not able to link one of free@home entities in Node Red. They are not visible/selectable in the list.

**Comment by Tho85** [comment]
Could you send a dump of your config file as described [in the README](https://github.com/jheling/freeathome#1-dumping-freehome-configuration), and the serial number of the devices that are not working as expected?

**Comment by JvD12** [comment]
Hi, I created the dump: https://paste.ubuntu.com/p/vNcKj966Yz 
Do you also have suggestions/ideas for Node Red integration?

**Comment by Tho85** [comment]
Hi, I've used your config and ran it through the component. For me, the generated device names are `binary_sensor.hvac` and `binary_sensor.input`. Could you try to remove the entities in Home Assistant under "Settings" -> "Entities" and restart Home Assistant? This should re-add the device and hopefully set a correct name.

I don't use Node-RED, so unfortunately I can't help with that.

Regarding other suggestions: The binary sensors will not work as you expect. This is not (only) due to the implementation in this component, but due to the firmware on the devices themselves. They track the state (on/off) of the devices they control internally, and so if you switch the devices through Home Assistant, the device will not know, and the state will be out of sync. I haven't found a stable configuration for this yet.

Here's how I control devices in Home Assistant through my in-wall switches: I configured the [emulated_hue](https://www.home-assistant.io/integrations/emulated_hue/) component, so that Home Assistant works as a Philips Hue bridge, and exposed some lights through it. I then added that Hue bridge to free@home, and the exposed lights showed up in free@home. I can then link my in-wall switches with the virtual Hue light bulbs and control them. Maybe you want to try something similar instead of reading the sensor values directly?

**Comment by JvD12** [comment]
Hi, thanks for the fast support! I forgot to "revert" some changes in the names. I had renamed the channels Ⓐ, ⓑ to hvac and bel. Can you test a new log also with the original naming? https://paste.ubuntu.com/p/2mvGWHr58h/

I have restarted the Free@home access point and Home Assistant systems several times without success.

**Comment by Tho85** [comment]
This is most probably an issue with Home Assistant core. If you name an entity Ⓐ or ⓑ, Home Assistant tries to make an alphanumeric entity name out of this, which fails. This also occurs if you create a new automation and name it Ⓐ - this will lead to an error: `homeassistant.exceptions.HomeAssistantError: Invalid entity id: automation.`

Maybe this can be fixed in HA core? I'll check. Quick workaround for this component for now is to just rename your devices ;-)

**Comment by EnricoBilla** [comment]
From what I've seen in [this regex](https://github.com/home-assistant/core/blob/6e9b65405a0559b8b04e9930fd6ad4193f72f68b/homeassistant/core.py#L125) it's only possible to use lowercase letters, digits and underscores

**Comment by Tho85** [comment]
I think the relevant code is [here (slugify)](https://github.com/home-assistant/core/blob/dev/homeassistant/util/__init__.py#L45-L48). [Here](https://github.com/home-assistant/core/blob/2af984917e7cf3ee649ed3a531a872e7aaeba713/tests/util/test_init.py#L28-L43) is the corresponding test. IMO it should return `_` if the string is empty after slugifying.

**Comment by EnricoBilla** [comment]
Yes you are right👍🏼

**Comment by Tho85** [comment]
I've opened an upstream PR, let's see how it turns out: home-assistant/core#43153

**Comment by miezie** [comment]
> I'm also not able to link one of free@home entities in Node Red. They are not visible/selectable in the list.

I checked my Node Red installation and noticed that I can just use the F@H components there. Eg. when I select a "Call Service" node I can just select F@H components in the dropdown. So it might be your configuration or set-up not working.

**Comment by JvD12** [comment]
Thanks for the support. I will test it next week.

**Comment by JvD12** [comment]
With the renamed Free@Home devices it works as expected.

I also tested the Node Red intergration. None of the Free@Home entities are shown in the  Entity ID list of Node Red. 
But If I put manually the correct entity name it works as intended. The Free@Home devices are visible in the Home Assistant entities ( configuration > entities) So I don't know were the problem occurs but with this manual workaround it fine for me.
