### ISSUE TITLE
[Question] Welcome IP-Gateway

### ISSUE THREAD

**Issue by christo-ph** [jheling/freeathome#85]
Hi,

the only device I have is the video doorbell which is able to notify me if someone is ringing, unlock the door and watch the cam.

It is not integrated in any free at home hub/router/gateway. I do have the IP-Gateway though. Is there any way to use this? Is there already any api doc available? 

Currently I am only able to use the app from Busch itself.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/16965068/102687037-60f9c100-41ec-11eb-8148-0ecf39bea2d0.png">

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/16965068/102687077-be8e0d80-41ec-11eb-82fe-fc5feb8a6e77.png">

Hope you can give me a hint. Thanks in advance.

**Comment by jheling** [comment]
You have probably googled a lot to find some information.  Maybe it does not exist yet. 
I know for the free@home system somebody used wireshark for figuring out which protocol was used.  Maybe you can intercept the traffic between the telephone and the ip-gateway.
And if the device has a web  interface is it sometimes possible to
use the web developer tools to look at the javascript code.

**Comment by christo-ph** [comment]
Thanks for your hints. I think I have to dive deeper here =)

**Comment by LorbusChris** [comment]
I know this issue is very old, but thought this might still be of interest for some folks:
You can integrate the IP-Gateway via SIP: You have to add a config for a Comfort Panel 3.0, and then on the receiving SIP end (PBX or softphone) use those credentials to gain access the AV. 

See (in German): https://community.busch-jaeger.de/frage-ansehen/ist-es-m-glich-den-rtsp-stream-von-welcome-abzufangen-f-r-integration-homekit-ber-homebridge-als-beispiel/focus/61d6107344680719aa4979c9#@61d6107344680719aa4979c9
